# This file is hosted at https://github.com/radical-cybertools/radical.pilot/tree/devel/docker
#
# See README.md in this directory for instructions.
#
# See https://docs.docker.com/compose/compose-file/ for reference information.

# version: "3.8"
# services:
#   mongodb:
#     image: mongo
#     container_name: mongodb
#   ports:
#     - 27017:27017
#   restart: unless-stopped

version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    # - PUID=1000
    # - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
#     - MONGO_INITDB_DATABASE=test
    ports:
      - "127.0.0.1:10000:27017"
    restart: unless-stopped
#
# # rabbitmq:
# #   image: rabbitmq
# #   container_name: 'rabbitmq'
# #   ports:
# #       - 10001:5672
# #       - 10002:15672

  login:
    image: shell
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/shell.dockerfile
    ports:
      - "127.0.0.1:2345:22"

