# This file is hosted at https://github.com/radical-cybertools/radical.pilot/tree/devel/docker
#
# See README.md in this directory for instructions.
#
# See https://docs.docker.com/compose/compose-file/ for reference information.

services:
  mongo:
    image: mongo:bionic
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  login:
    image: radicalpilot
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/radicalpilot.dockerfile
#    ports:
#      - "127.0.0.1:2345:22"
