# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# pylint: disable=redefined-builtin

# -- Project information -----------------------------------------------------

project = 'RADICAL-Pilot'
copyright = '2025, The RADICAL-Cybertools Team (info@radical-cybertools.org)'
author = 'RADICAL-Cybertools Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
with open('../../VERSION', 'r', encoding='utf-8') as f:
    version = str(f.readlines()[0])
# The full version, including alpha/beta/rc tags.
with open('../../VERSION', 'r', encoding='utf-8') as f:
    release = str(f.readlines()[0])

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'nbsphinx',
    'sphinx_copybutton',
    'sphinx_rtd_theme',
    'sphinx.ext.napoleon',
    'sphinx.ext.imgconverter',
    'myst_parser'
]


github_token = os.environ.get("GITHUB_TOKEN")

if github_token:
    extensions.append('rtds_action')


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# exclude_patterns = ['3/*.ipynb']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = "armstrong"
html_theme = "sphinx_rtd_theme"
html_theme_path = ["_themes", ]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    "https://docs.python.org/3/": None,
    "https://radicalsaga.readthedocs.io/en/stable/": None,
    "https://radicalutils.readthedocs.io/en/stable": None,
    "https://msgpack-python.readthedocs.io/en/latest/": None,
    "https://mpi4py.readthedocs.io/en/stable/": None,
}

# -- Napoleon settings -------------------------------------------------------
# Reference https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
napoleon_google_docstring = True
napoleon_numpy_docstring = False
# napoleon_include_init_with_doc = False
# napoleon_include_private_with_doc = False
# napoleon_include_special_with_doc = True
# napoleon_use_admonition_for_examples = False
# napoleon_use_admonition_for_notes = False
# napoleon_use_admonition_for_references = False
# napoleon_use_ivar = False
# napoleon_use_param = True
# napoleon_use_rtype = True
# napoleon_preprocess_types = False
# napoleon_type_aliases = None
# napoleon_attr_annotations = True

# -- rtds settings -------------------------------------------------------------
# The "prefix" used in the `upload-artifact` step of the action
if github_token:
    rtds_action_github_repo      = "radical-cybertools/radical.pilot"
    rtds_action_github_token     = github_token
    rtds_action_artifact_prefix  = "rtd-"
    rtds_action_error_if_missing = False

