name: Comet Integration Test

on:
  repository_dispatch:
    types: [ test_comet ]
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  inter_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Check event
      if: github.event.client_payload.text
      run: |
        echo "Event text: ${{ github.event.client_payload.text }}"
        if [ ${{ github.event.client_payload.text }} == "success" ]
        then
            echo "Success"
        else
            echo "Failure"
            false
        fi
  periodic_jobs:
    if: github.event.client_payload.text == null
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Cron
      run: |
        tests/bin/radical-pilot-test-verify -y 'comet' -d 7
