name: 'Run RP Jupyter notebook'

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version for running the Jupyter notebook'
        required: true
        type: string
      requirements-file:
        description: 'File with dependencies'
        required: false
        default: 'requirements-docs.txt'
        type: string
      notebook-name:
        description: 'File name of the Jupyter notebook'
        required: true
        type: string
      documentation-path:
        description: 'Path of the documentation in the repository'
        required: false
        default: 'docs/source'
        type: string
      notebook-path:
        description: 'Path of the Jupyter notebook within the documentation'
        required: false
        default: ''
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update -y && sudo apt install -y openmpi-bin libopenmpi-dev
          python -m venv testenv
          . testenv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r ${{ inputs.requirements-file }}
          python -m pip install jupyter
      - name: Run Jupyter Notebook
        env:
          TARGET_PATH: ${{ format('{0}/{1}/{2}', inputs.documentation-path, inputs.notebook-path, inputs.notebook-name) }}
          RADICAL_LOG_LVL: DEBUG
          RADICAL_PILOT_OVERSUBSCRIBE=1
        timeout-minutes: 10
        # continue-on-error: true
        run: |
          . testenv/bin/activate
          jupyter nbconvert --clear-output --inplace $TARGET_PATH
          jupyter nbconvert --to notebook --execute --inplace $TARGET_PATH
      - name: Collect sessions
        if: always()
        run: |
          SID=$(find . -name "rp.session*" -type d -exec basename {} "rp.session" \;)
          test -z "$SID" && echo 'Session not created' && exit 0
          AGENT_SBOX="$HOME/radical.pilot.sandbox/$SID"
          CLIENT_NAME="${{ inputs.notebook-name }}_client_$SID"
          AGENT_NAME="${{ inputs.notebook-name }}_agent_$SID"
          echo "SID         : $SID"
          echo "AGENT_SBOX  : $AGENT_SBOX"
          echo "CLIENT_NAME : $CLIENT_NAME"
          echo "AGENT_NAME  : $AGENT_NAME"
          mkdir sessions_notebooks
          tar -cjf sessions_notebooks/$CLIENT_NAME.tar.bz2 $SID && \
              echo "Client tarball created OK" || echo "NO client tarball"
          if [ -d "$AGENT_SBOX" ]; then
            tar -cjf sessions_notebooks/$AGENT_NAME.tar.bz2 -P $AGENT_SBOX && \
                echo "Agent tarball created OK" || echo "NO agent tarball"
          fi
      - name: Upload sessions
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: sessions_notebooks_${{inputs.notebook-name}}_${{inputs.python-version}}
            path: sessions_notebooks
            retention-days: 5
            overwrite: true
